export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  USERS: 'USERS',

  POST: 'POST',
  POST_ADD: 'POST_ADD',
  POST_LIST: 'POST_LIST',
  POST_DETAIL: 'POST_DETAIL',
  POST_EDIT: 'POST_EDIT',

  CATEGORY: 'CATEGORY',
  CATEGORY_ADD: 'CATEGORY_ADD',
  CATEGORY_LIST: 'CATEGORY_LIST',
  CATEGORY_EDIT: 'CATEGORY_EDIT',

  DEMO: 'DEMO',
  DEMO_LIST: 'DEMO_LIST',
  DEMO_DETAIL: 'DEMO_DETAIL',

  CONTACT: 'CONTACT',
  CONTACT_LIST: 'CONTACT_LIST',
  CONTACT_DETAIL: 'CONTACT_EDIT',

  PARTNER: 'PARTNER',
  PARTNER_LIST: 'PARTNER_LIST',
  PARTNER_ADD: 'PARTNER_ADD',
  PARTNER_EDIT: 'PARTNER_EDIT',

  TOOLSMANAGES: 'TOOLSMANAGES',
  TOOLSMANAGES_LIST: 'TOOLSMANAGES_LIST',
  TOOLSMANAGES_ADD: 'TOOLSMANAGES_ADD',
  TOOLSMANAGES_EDIT: 'TOOLSMANAGES_EDIT',
};
